Item slot model
Prakkkmak/Space-Station-Lambda pull request #154
Opened 2021-07-18 19:23 UTC by Nowp

Adding the preview of ItemStacks model in the hotbar

2021-07-19 16:30 UTC, Prakkkmak requested changes

2021-07-19 16:30 UTC, Prakkkmak commented on code/UI/InventoryBar.cs
> +                    }
invert
et return
```suggestion
                    if (player.Inventory.IsSlotEmpty(SlotNumber)) return;
                    
                        Model model = Model.Load("models/knife/knife.vmdl");
                        sceneObject = new SceneObject(model, Transform.Zero);
                        sceneLight = Light.Point(Vector3.Up * 10.0f + Vector3.Forward * 100.0f - Vector3.Right * 100.0f,
                            2000, Color.White * 15000.0f);
                    
```

2021-07-19 16:30 UTC, Prakkkmak commented on code/UI/InventoryBar.cs
> +                Angles angles = new(30, 180+45, 0);
Magic number avec valeurs constante
s

2021-07-19 16:30 UTC, Prakkkmak commented on code/UI/InventoryBar.cs
> +                Vector3 pos = new(10, 10, 10);
Magic number avec valeurs constante

2021-07-19 16:30 UTC, Prakkkmak commented on code/UI/InventoryBar.scss
> +
```suggestion
```

2021-07-19 16:30 UTC, Prakkkmak commented on code/UI/InventoryBar.scss
> +    margin-right: 5px;
margin 2px

2021-07-19 16:30 UTC, Prakkkmak commented on code/UI/InventoryBar.scss
> +      left: 7px;
```suggestion
```

2021-07-29 11:37 UTC, Prakkkmak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Item slot model](https://trello.com/c/wgaBwZol/50-item-slot-model)

2021-07-29 13:02 UTC, Prakkkmak commented on code/UI/InventoryBar.cs
> +                    scene.World = sceneWorld;
ca marche scene?.World = sceneWorld ?

2021-07-29 13:17 UTC, Nowp commented on code/UI/InventoryBar.cs
> +            }
Nope no linq

2021-07-29 13:18 UTC, Nowp commented on code/UI/InventoryBar.cs
> +                    scene.World = sceneWorld;
Nope it's in a if-else structure

2021-07-30 17:08 UTC, Prakkkmak approved these changes

2021-07-30 17:09 UTC, merged