Fix Inventory sync client side
Prakkkmak/Space-Station-Lambda pull request #156
Opened 2021-07-18 22:34 UTC by Nowp

2021-07-19 11:48 UTC, Prakkkmak requested changes

2021-07-19 11:48 UTC, Prakkkmak commented on code/Items/Inventory.cs
> +
```suggestion
```

2021-07-19 11:48 UTC, Prakkkmak commented on code/Items/Inventory.cs
> +        [Net] public List<ItemStack> Items { get; private set; }
Pourquoi passer en liste quand on connais la taille ?

2021-07-19 11:49 UTC, Nowp commented on code/Items/Inventory.cs
> +        [Net] public List<ItemStack> Items { get; private set; }
Ca a pas l'air d'être network si c'est pas une liste (source: les mecs sur Sbox)

2021-07-19 12:10 UTC, Nowp commented on code/Items/Inventory.cs
> +        [Net] public List<ItemStack> Items { get; private set; }
Je referai des tests pour être sûr qu'ils m'ont pas juste dit "Utilise une list lolilol"

2021-07-19 16:21 UTC, Prakkkmak requested changes
List to private and don't let people ADD new elemnt

2021-07-21 17:20 UTC, Prakkkmak approved these changes

2021-07-21 17:57 UTC, merged