Ragdoll on death
Prakkkmak/Space-Station-Lambda pull request #204
Opened 2021-07-29 16:03 UTC by Nowp

2021-07-29 16:09 UTC, Nowp commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ragdoll on death](https://trello.com/c/spFE3r8g/54-ragdoll-on-death)

2021-07-29 17:25 UTC, Prakkkmak requested changes

2021-07-29 17:25 UTC, Prakkkmak commented on code/Player/MainPlayer.cs
> +            Log.Info($"Health: {Health}");
```suggestion
```

2021-07-29 17:25 UTC, Prakkkmak commented on code/Player/MainPlayer.cs
> +
```suggestion
```

2021-07-29 17:25 UTC, Prakkkmak commented on code/Entities/PlayerCorpse.cs
> +					body.ApplyForce( force * 1000 );
magic number

2021-07-29 17:25 UTC, Prakkkmak commented on code/Entities/PlayerCorpse.cs
> +					if (model != null && !model.Contains("clothes"))
magic string

2021-07-30 20:08 UTC, Prakkkmak requested changes
pas fais

2021-07-30 21:03 UTC, Prakkkmak approved these changes

2021-07-30 22:44 UTC, merged