PostRound screen
Prakkkmak/Space-Station-Lambda pull request #290
Opened 2021-09-02 16:38 UTC by Nowp

2021-09-02 17:04 UTC, Prakkkmak commented on code/Modules/Rounds/InProgressRound.cs
> +                if (mainPlayer.RoleHandler.Role.Id == TraitorId) numberOfTraitors++;
```suggestion
                if (mainPlayer.RoleHandler.Role is Traitor) numberOfTraitors++;
```

2021-09-02 17:06 UTC, Prakkkmak commented on code/Ui/GameResults/GameResults.cs
> +            if (currentRound == null) return;
null ==

2021-09-02 17:08 UTC, Prakkkmak requested changes
commented

2021-09-02 23:17 UTC, Nowp commented on code/Ui/GameResults/GameResults.cs
> +            if (currentRound == null) return;
```suggestion
            if (null == currentRound) return;
```

2021-09-03 14:36 UTC, Prakkkmak approved these changes

2021-09-03 14:36 UTC, merged