Machine props classes
Prakkkmak/Space-Station-Lambda pull request #352
Opened 2021-09-26 13:57 UTC by Prakkkmak

2021-09-26 14:06 UTC, NoePolytech requested changes
We implement machines now ?

2021-09-26 14:06 UTC, NoePolytech commented on code/Modules/Props/Data/MachineData.cs
> +        /// Determine the skill needed for repair the machine
```suggestion
        /// Determine the skill needed to repair the machine
```

2021-09-26 14:06 UTC, NoePolytech commented on code/Modules/Props/Data/MachineData.cs
> +        /// Durability of the machine. More durability = harder to destroy and mode time to repair
```suggestion
        /// Durability of the machine. More durability = harder to destroy and more time to repair
```

2021-09-26 14:06 UTC, NoePolytech commented on code/Modules/Props/Types/Machine.cs
> +        /// <param name="value">The damage reapaired</param>
```suggestion
        /// <param name="value">The damage repaired</param>
```

2021-09-26 14:06 UTC, NoePolytech commented on code/Modules/Props/Types/Machine.cs
> +        /// When the machine get hits
```suggestion
        /// When the machine is being repaired
```

2021-09-26 14:06 UTC, NoePolytech commented on code/Modules/Props/Types/Machine.cs
> +        private int health = 10;
Use the Health property already on the entity.
It may even be overriden in the Prop class alongside the OnTakeDamage etc methods

2021-10-04 21:10 UTC, Nowp approved these changes

2021-10-04 21:10 UTC, merged