feat: freeze player on end round
Prakkkmak/Space-Station-Lambda pull request #379
Opened 2021-11-04 18:13 UTC by Prakkkmak

2021-11-04 19:16 UTC, Nowp requested changes

2021-11-04 19:16 UTC, Nowp commented on code/Player/Controllers/HumanController.cs
> +            if (!Player.RagdollHandler.IsRagdoll && !IsFrozen)
On devrait check IsFrozen pour les deux trucs parce qu'on veut pas que le mec puisse se relever s'il est frozen

2021-11-04 19:16 UTC, Nowp commented on code/Player/MainPlayer.cs
> +        }
Pas con du tout, faudra faire ça pour les props

2021-11-08 07:28 UTC, Prakkkmak commented on code/Player/Controllers/HumanController.cs
> +            if (!Player.RagdollHandler.IsRagdoll && !IsFrozen)
Pour les deux trucs ?

2021-11-08 07:28 UTC, Prakkkmak commented on code/Player/MainPlayer.cs
> +        }
<3

2021-11-08 17:28 UTC, Nowp commented on code/Player/Controllers/HumanController.cs
> +            if (!Player.RagdollHandler.IsRagdoll && !IsFrozen)
Ouaip, si le joueur est freeze il a pas à se relever quand il est au sol

2021-11-08 20:58 UTC, Nowp approved these changes

2021-11-12 14:52 UTC, merged