WIP: refactor(ui): role selector
Prakkkmak/Space-Station-Lambda pull request #398
Opened 2021-12-15 13:18 UTC by Hiily

2021-12-15 17:38 UTC, Prakkkmak requested changes

2021-12-15 17:38 UTC, Prakkkmak commented on code/Ui/RoleSelector/RoleSelector.scss
> +  background-color: #282828;
Pourquoi ne pas utiliser une constante ?

2021-12-15 17:38 UTC, Prakkkmak commented on code/Ui/RoleSelector/RoleSlot.cs
> +		var inside = Add.Panel( "inside");
Ne pas utiliser var ; préferer explicit.

2021-12-23 21:24 UTC, Nowp commented on code/Ui/RoleSelector/RoleSlot.cs
> +		var inside = Add.Panel( "inside");
on a pas exporter nos configs de code style ? ça pourrait servir

2021-12-24 08:19 UTC, Hiily commented on code/Ui/RoleSelector/RoleSelector.scss
> +  background-color: #282828;
done :)

2021-12-24 08:19 UTC, Hiily commented on code/Ui/RoleSelector/RoleSlot.cs
> +		var inside = Add.Panel( "inside");
done :)

2021-12-24 18:53 UTC, Nowp commented on code/Ui/RoleSelector/RoleSlot.cs
> +		}
C'est pour structurer le code les accolades ou il y a une raison technique ?

2021-12-25 19:58 UTC, Hiily commented on code/Ui/RoleSelector/RoleSlot.cs
> +		}
vu en voc :)

2021-12-26 11:47 UTC, Prakkkmak approved these changes

2021-12-26 14:54 UTC, merged